<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="4" passed="0" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-06T15:01:12 IST" name="Default suite" finished-at="2022-06-06T15:02:05 IST" duration-ms="52991">
    <groups>
    </groups>
    <test started-at="2022-06-06T15:01:12 IST" name="Default test" finished-at="2022-06-06T15:02:05 IST" duration-ms="52991">
      <class name="com.qa.LoginPageTest.WishupLoginTest_DataProvider">
        <test-method is-config="true" signature="extentSetup()[pri:0, instance:com.qa.LoginPageTest.WishupLoginTest_DataProvider@5e0826e7]" started-at="2022-06-06T15:01:12 IST" name="extentSetup" finished-at="2022-06-06T15:01:12 IST" duration-ms="304" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentSetup -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.qa.LoginPageTest.WishupLoginTest_DataProvider@5e0826e7]" started-at="2022-06-06T15:01:12 IST" name="setup" finished-at="2022-06-06T15:01:33 IST" duration-ms="20246" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="validDataLoginTest(java.lang.String,java.lang.String,java.lang.String)[pri:11, instance:com.qa.LoginPageTest.WishupLoginTest_DataProvider@5e0826e7]" started-at="2022-06-06T15:01:33 IST" name="validDataLoginTest" data-provider="ValidTestData" finished-at="2022-06-06T15:01:46 IST" duration-ms="13415" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[wishup_testuser1@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[testpw1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[valid]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect [Add a task] but found [Add a task]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect [Add a task] but found [Add a task]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at org.testng.Assert.assertNotEquals(Assert.java:1535)
at com.qa.LoginPageTest.WishupLoginTest_DataProvider.validDataLoginTest(WishupLoginTest_DataProvider.java:49)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validDataLoginTest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.qa.LoginPageTest.WishupLoginTest_DataProvider@5e0826e7]" started-at="2022-06-06T15:01:46 IST" name="tearDown" finished-at="2022-06-06T15:01:46 IST" duration-ms="12" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validDataLoginTest status=FAILURE method=WishupLoginTest_DataProvider.validDataLoginTest(java.lang.String,java.lang.String,java.lang.String)[pri:11, instance:com.qa.LoginPageTest.WishupLoginTest_DataProvider@5e0826e7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="validDataLoginTest(java.lang.String,java.lang.String,java.lang.String)[pri:11, instance:com.qa.LoginPageTest.WishupLoginTest_DataProvider@5e0826e7]" started-at="2022-06-06T15:01:46 IST" name="validDataLoginTest" data-provider="ValidTestData" finished-at="2022-06-06T15:01:55 IST" duration-ms="9248" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[wishup_testuser3@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[testpw3]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[valid]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect [Add a task] but found [Add a task]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect [Add a task] but found [Add a task]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at org.testng.Assert.assertNotEquals(Assert.java:1535)
at com.qa.LoginPageTest.WishupLoginTest_DataProvider.validDataLoginTest(WishupLoginTest_DataProvider.java:49)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validDataLoginTest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.qa.LoginPageTest.WishupLoginTest_DataProvider@5e0826e7]" started-at="2022-06-06T15:01:55 IST" name="tearDown" finished-at="2022-06-06T15:01:55 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validDataLoginTest status=FAILURE method=WishupLoginTest_DataProvider.validDataLoginTest(java.lang.String,java.lang.String,java.lang.String)[pri:11, instance:com.qa.LoginPageTest.WishupLoginTest_DataProvider@5e0826e7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="validDataLoginTest(java.lang.String,java.lang.String,java.lang.String)[pri:11, instance:com.qa.LoginPageTest.WishupLoginTest_DataProvider@5e0826e7]" started-at="2022-06-06T15:01:55 IST" name="validDataLoginTest" data-provider="ValidTestData" finished-at="2022-06-06T15:02:05 IST" duration-ms="9765" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[wishup_testuser4@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[testpw4]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[valid]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect [Add a task] but found [Add a task]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect [Add a task] but found [Add a task]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at org.testng.Assert.assertNotEquals(Assert.java:1535)
at com.qa.LoginPageTest.WishupLoginTest_DataProvider.validDataLoginTest(WishupLoginTest_DataProvider.java:49)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validDataLoginTest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.qa.LoginPageTest.WishupLoginTest_DataProvider@5e0826e7]" started-at="2022-06-06T15:02:05 IST" name="tearDown" finished-at="2022-06-06T15:02:05 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validDataLoginTest status=FAILURE method=WishupLoginTest_DataProvider.validDataLoginTest(java.lang.String,java.lang.String,java.lang.String)[pri:11, instance:com.qa.LoginPageTest.WishupLoginTest_DataProvider@5e0826e7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="driverTearDown()[pri:0, instance:com.qa.LoginPageTest.WishupLoginTest_DataProvider@5e0826e7]" started-at="2022-06-06T15:02:05 IST" name="driverTearDown" finished-at="2022-06-06T15:02:05 IST" duration-ms="238" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverTearDown -->
        <test-method is-config="true" signature="extentReportTearDown()[pri:0, instance:com.qa.LoginPageTest.WishupLoginTest_DataProvider@5e0826e7]" started-at="2022-06-06T15:02:05 IST" name="extentReportTearDown" finished-at="2022-06-06T15:02:06 IST" duration-ms="753" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentReportTearDown -->
      </class> <!-- com.qa.LoginPageTest.WishupLoginTest_DataProvider -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
